fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0341/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0342/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0343/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0344/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0345/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0346/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0347/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0348/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0349/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0350/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0352/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0354/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0355/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0356/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0267/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0268/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0270/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0271/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0272/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0273/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0274/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0278/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0279/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0281/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0286/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0288/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0289/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0291/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0292/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0293/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0300/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0301/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0302/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0303/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0304/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0306/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0307/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0309/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0310/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0311/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0312/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0315/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0317/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0318/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0322/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0323/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0325/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0326/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0328/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0329/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0332/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0333/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0336/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0337/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0215/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0218/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0219/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0220/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0222/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0224/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0225/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0226/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0227/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0228/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0229/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0230/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0232/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0235/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0236/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0238/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0239/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0243/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0245/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0247/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0248/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0249/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0254/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0258/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0259/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0260/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0261/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0263/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0265/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0184/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0187/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0192/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0193/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0194/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0195/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0196/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0199/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0200/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0203/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0204/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0205/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0208/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0209/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0210/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0211/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0213/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0114/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0115/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0116/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0126/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0127/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0128/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0129/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0133/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0134/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0135/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0136/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0137/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0139/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0143/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0144/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0145/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0149/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0150/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0151/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0153/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0154/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0155/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0156/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0157/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0158/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0159/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0161/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0162/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0164/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0165/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0166/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0167/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0169/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0171/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0173/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0174/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0175/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0176/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0178/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0183/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0069/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0072/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0078/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0082/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0083/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0084/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0085/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0086/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0087/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0088/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0089/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0090/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0096/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0097/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0098/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0099/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0101/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0103/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0104/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0107/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0110/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0112/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0113/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0014/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0004/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0009/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0018/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0022/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0001/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0026/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0028/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0034/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0036/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0037/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0038/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0042/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0045/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0047/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0048/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0049/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0050/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0053/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0054/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0058/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0060/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0065/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0066/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0067/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0357/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0358/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0024/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt
fix -a /corral-repl/utexas/poldracklab/data/gene_study/G1_0130/raw/BOLD_resting/BOLD_processed_rest_ica.ica/fix4melview_TRAINING2_thr20.txt

